### PR TITLE
Added ContactUs/Email feature

### PR DESCRIPTION
**Pull request by kumarakash101**
**What changes have I made?**
I added the feature of Contact Us page in which a user can contact/ask a question to the developers of the website and his query will be come to the developers in the form of an email.

**Why did I make these changes?**
I made these changes as a part of my second sprint which is adding a feature described in the issues section under my name.

**What feedback I am looking for from you?**
Please share any sort of feedback related to design, code improvisation or any folder structure changes.

Capture3

Capture2

### CODE REVIEW

**Comment by juhiaugustine** [comment]
The implementation looks good but can you improve the CSS a little bit. It looks very plain and hard to see the form. Can you  make the form bigger and visible with probably a little background?

**Review by juhiaugustine — CHANGES_REQUESTED** [review]
Added minor comments. Feel free to reach out if you have any questions

**Comment by kumarakash101** [comment]
Requested changes made and added a Reset button also
Capture2

**Review by kumarakash101 — COMMENTED** [review]
Done

**Pull request merged**
