### PR TITLE
Added Mars Rover photos component to Home page

### PR DESCRIPTION
**Pull request by juhiaugustine**
### What changes have I made?
I have added a mars rover photos component which is a horizontal scroller containing rover photos from Mars. The images are fetched from Mars Rover Photos API and I have used axios library to make the network call.

### What feedback I am looking for from you?
Please share any sort of feedback related to design, code improvisation or any folder structure changes.

### Screenshot
image

### CODE REVIEW

**Comment by kumarakash101** [comment]
Looks good, thank you for the changes, finally our project is getting loaded with more and more features.

**Review by kumarakash101 — APPROVED** [review]

**Comment by shrutivd** [comment]
The code and the display both look good.  
I have one suggestion. We should add the API key in a separate file (for example in .env) for security reasons and as a good practice.

**Review by shrutivd — APPROVED** [review]

**Comment by shrutivd** [comment]
The text "Mars rover photos" looks like a website title.  You might have added it temporarily, but we need to have our project title "Space Explorer" instead of that text, and maybe you can display that text, with a smaller font size on the left side.

**Comment by juhiaugustine** [comment]
> The text "Mars rover photos" looks like a website title. You might have added it temporarily, but we need to have our project title "Space Explorer" instead of that text, and maybe you can display that text, with a smaller font size on the left side.

Updated styling changes suggested by you. Thanks for the feedback.

image

**Pull request merged**
